releases:
- name: oms-agent-for-linux
  version: 1.12.15-0
  url: https://github.com/Azure/oms-agent-for-linux-boshrelease/releases/download/v1.4.2-125/oms-agent-for-linux-1.4.2-125.tgz
addons:
- name: omsagent
  jobs:
  - name: omsagent
    release: oms-agent-for-linux
  exclude:
    stemcell:
    - os: windows2012R2
    - os: windows2016
    - os: windows2019
    - os: windows1803
  properties:
    # Get the OMS workspace ID and key from OMS Portal
    oms:
      workspace_id: CHANGE_ME
      workspace_key: CHANGE_ME
      top_level_domain: opinsights.azure.com # opinsights.azure.us for Azure US Government
    # Modify the config as needed, if no rsyslog config is specifed, the default rsyslog config of omsagent will be used
    rsyslog:
      selector_list:
      - user.*     
      - syslog.*
      port: 25224
      protocol_type: udp

