releases:
- name: oms-agent-for-linux
  version: 1.4.1-125
  url: https://github.com/Azure/oms-agent-for-linux-boshrelease/releases/download/v1.4.1-125/oms-agent-for-linux-1.4.1-125.tgz
addons:
- name: omsagent
  jobs:
  - name: omsagent
    release: oms-agent-for-linux
  exclude:
    stemcell:
    - os: windows2012R2
  properties:
    # Get the OMS workspace ID and key from OMS Portal
    oms:
      workspace_id: CHANGE_ME
      workspace_key: CHANGE_ME
    # Modify the config as needed, if no rsyslog config is specifed, the default rsyslog config of omsagent will be used
    rsyslog:
      selector_list:
      - user.*     
      - syslog.*
      port: 25224
      protocol_type: udp

